// flow-typed signature: 53790bcda5b74cf41def7f56a86c6cc5
// flow-typed version: <<STUB>>/cfonts_v^2.1.3/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cfonts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cfonts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cfonts/bin/index' {
  declare module.exports: any;
}

declare module 'cfonts/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cfonts/bin/index.js' {
  declare module.exports: $Exports<'cfonts/bin/index'>;
}
declare module 'cfonts/lib/index.js' {
  declare module.exports: $Exports<'cfonts/lib/index'>;
}
