// flow-typed signature: 5e47ea69441653f79e3d8f0bb8a2989a
// flow-typed version: <<STUB>>/electron-notifications_v^1.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-notifications'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-notifications' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-notifications/lib/app' {
  declare module.exports: any;
}

declare module 'electron-notifications/lib/behaviors/clickBehavior' {
  declare module.exports: any;
}

declare module 'electron-notifications/lib/behaviors/swipeRightBehavior' {
  declare module.exports: any;
}

declare module 'electron-notifications/lib/notification' {
  declare module.exports: any;
}

declare module 'electron-notifications/lib/notificationView' {
  declare module.exports: any;
}

declare module 'electron-notifications/lib/notifier' {
  declare module.exports: any;
}

declare module 'electron-notifications/playbook/assets/run' {
  declare module.exports: any;
}

declare module 'electron-notifications/playbook/assets/vendor/codemirror-js' {
  declare module.exports: any;
}

declare module 'electron-notifications/playbook/assets/vendor/codemirror' {
  declare module.exports: any;
}

declare module 'electron-notifications/playbook/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-notifications/index' {
  declare module.exports: $Exports<'electron-notifications'>;
}
declare module 'electron-notifications/index.js' {
  declare module.exports: $Exports<'electron-notifications'>;
}
declare module 'electron-notifications/lib/app.js' {
  declare module.exports: $Exports<'electron-notifications/lib/app'>;
}
declare module 'electron-notifications/lib/behaviors/clickBehavior.js' {
  declare module.exports: $Exports<'electron-notifications/lib/behaviors/clickBehavior'>;
}
declare module 'electron-notifications/lib/behaviors/swipeRightBehavior.js' {
  declare module.exports: $Exports<'electron-notifications/lib/behaviors/swipeRightBehavior'>;
}
declare module 'electron-notifications/lib/notification.js' {
  declare module.exports: $Exports<'electron-notifications/lib/notification'>;
}
declare module 'electron-notifications/lib/notificationView.js' {
  declare module.exports: $Exports<'electron-notifications/lib/notificationView'>;
}
declare module 'electron-notifications/lib/notifier.js' {
  declare module.exports: $Exports<'electron-notifications/lib/notifier'>;
}
declare module 'electron-notifications/playbook/assets/run.js' {
  declare module.exports: $Exports<'electron-notifications/playbook/assets/run'>;
}
declare module 'electron-notifications/playbook/assets/vendor/codemirror-js.js' {
  declare module.exports: $Exports<'electron-notifications/playbook/assets/vendor/codemirror-js'>;
}
declare module 'electron-notifications/playbook/assets/vendor/codemirror.js' {
  declare module.exports: $Exports<'electron-notifications/playbook/assets/vendor/codemirror'>;
}
declare module 'electron-notifications/playbook/main.js' {
  declare module.exports: $Exports<'electron-notifications/playbook/main'>;
}
