// flow-typed signature: afa4cc90da0879b4cc8c18c8741249f6
// flow-typed version: <<STUB>>/mysterium-client-bin_v^0.2.3/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mysterium-client-bin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mysterium-client-bin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mysterium-client-bin/index' {
  declare module.exports: $Exports<'mysterium-client-bin'>;
}
declare module 'mysterium-client-bin/index.js' {
  declare module.exports: $Exports<'mysterium-client-bin'>;
}
