// flow-typed signature: 780645ecc071b818a9577d39af90e3ea
// flow-typed version: <<STUB>>/os-name_v^2.0.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'os-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'os-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'os-name/index' {
  declare module.exports: $Exports<'os-name'>;
}
declare module 'os-name/index.js' {
  declare module.exports: $Exports<'os-name'>;
}
