// flow-typed signature: 438dbd41314ec7312fe0fc5b18577f3e
// flow-typed version: <<STUB>>/vue-multiselect_v^2.0.8/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-multiselect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-multiselect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-multiselect/dist/vue-multiselect.min' {
  declare module.exports: any;
}

declare module 'vue-multiselect/src/index' {
  declare module.exports: any;
}

declare module 'vue-multiselect/src/multiselectMixin' {
  declare module.exports: any;
}

declare module 'vue-multiselect/src/pointerMixin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-multiselect/dist/vue-multiselect.min.js' {
  declare module.exports: $Exports<'vue-multiselect/dist/vue-multiselect.min'>;
}
declare module 'vue-multiselect/src/index.js' {
  declare module.exports: $Exports<'vue-multiselect/src/index'>;
}
declare module 'vue-multiselect/src/multiselectMixin.js' {
  declare module.exports: $Exports<'vue-multiselect/src/multiselectMixin'>;
}
declare module 'vue-multiselect/src/pointerMixin.js' {
  declare module.exports: $Exports<'vue-multiselect/src/pointerMixin'>;
}
